### ISSUE TITLE
Question: probMap probMapSaddles have the same value?

### ISSUE THREAD

**Issue by BMaxV** [oargudo/orometry-terrains#3]
Hi,

your code "works on my machine" now, thank you very much for sharing it!

I did some rewriting to be able to use it from the command line instead of from jupyter notebooks. I have not really changed anything about the calculations, so the original notebooks also still work.

But to the question:

in block 13 in Synthesis.ipynb , these two variables have the same value, but I'm assuming they're used in different places for different purposes? Was this intentional?

```
probMap = (imgControlDensity - imgControlDensity.min())/(imgControlDensity.max() - imgControlDensity.min())
probMapSaddles = (imgControlDensity - imgControlDensity.min())/(imgControlDensity.max() - imgControlDensity.min())
```

sorry for the weird link https://github.com/oargudo/orometry-terrains/blob/master/Synthesis.ipynb?short_path=d230ade#L275

**Comment by oargudo** [comment]
Hi,

Yes, in this particular example they do have the same value because I was using just one .png file as probability map ('input/user_probs.png'). But you could use two different probability maps if it makes sense to do so. For example, you could compute from a real location a density map of where the saddles are located, and another one from where the peaks are, and give these two separate maps to synthDivideTree(...).
Recall that this is a "more or less cleaned" version of our research code as is, and we did plenty of experiments, some of which didn't work out entirely well and were discarded. If you track this parameter down the function calls, you'll arrive here with a comment thay says it was not very useful :)
[https://github.com/oargudo/orometry-terrains/blob/e48354e60babfbb8c53e3d3b2b94559c30941484/synthesis/divtree_synthesis.py#L132](https://github.com/oargudo/orometry-terrains/blob/e48354e60babfbb8c53e3d3b2b94559c30941484/synthesis/divtree_synthesis.py#L132)

**Comment by BMaxV** [comment]
Alright, that explains it. Thanks!
